In [1]:
import numpy as np
from sklearn.decomposition import NMF
import pandas as pd

In [2]:
# movie, ratings by users
data = [
    [5, 4, 1, 1, 3],
    [3, 2, 1, 3, 1],
    [3, 3, 3, 3, 5],
    [1, 1, 5, 4, 4],
]
columns = ['Titanic', 'Tiffany', 'Terminator', 'Star Trek', 'Star Wars'] #movies
index = ['Ada', 'Bob', 'Steve', 'Margaret'] #users


In [3]:
#need a dataframe for this
R = pd.DataFrame(data, index=index, columns=columns).values

In [6]:
#20 genres for the hidden space in movies

In [7]:
#create a model and set the hyperparameters
# model assumes R ~ PQ'
model = NMF(n_components=2, init='random', random_state=10)

In [8]:
model.fit(R)

NMF(alpha=0.0, beta_loss='frobenius', init='random', l1_ratio=0.0, max_iter=200,
    n_components=2, random_state=10, shuffle=False, solver='cd', tol=0.0001,
    verbose=0)

In [9]:
Q = model.components_  # movie-genre matrix

In [11]:
P = model.transform(R)  # user-genre matrix

In [13]:
print(model.reconstruction_err_) #reconstruction error

2.319822011025


In [14]:
nR = np.dot(P, Q)
print(nR) ## The reconstructed matrix!

[[4.98574011 3.98089613 0.69817861 1.52507923 2.84430572]
 [2.61580597 2.15486368 1.23495386 1.51110529 2.19736573]
 [3.35829506 2.89944467 3.32824145 3.36641177 4.23566511]
 [0.85105386 1.03300314 4.75334969 4.0532461  4.24705685]]


In [15]:
#Scikit learn does not ignore NaNs while calculating MSE

In [16]:
#Write own gradient descent - where the error function is ignoring the empty spaces in matrix

In [17]:
#Pickle

In [18]:
#Histogram of ratings